name = "EOTW Reloaded"
author = "TheMade4"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3cf5d1f205890115b5276198988ba682c2ddba520dce899476823a9684829fb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
