name = "EOTW Reloaded"
author = "TheMade4"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e914502f126bcbf39ab0c9a8e2179bbbe0e6888aca7730e18c5de393f341cae"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
