name = "EOTW Reloaded"
author = "TheMade4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf34ae93d9de3353efbdf51883562874c34fa7ec69a20b72066cf275578751b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
